#!/usr/bin/env sh

cd ~

# Pull and install Chromebrew Package Manager
wget -q -O - https://raw.github.com/skycocker/chromebrew/master/install.sh | bash

crew install vim
crew install python34
# Remove readline as it breaks things with vim (MAY HAVE BEEN FIXED)
#sudo crew remove readline

# Install Vundle
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

# Download crouton
wget -q -O ~/Downloads/crouton https://github.com/dnschneid/crouton/blob/master/installer/crouton
